// src/notes/BaseFile.ts
// Lazy LeetCode.base writer. Ships ONCE on the first Phase-2 problem open
// (D-18) and never again — users may customise the YAML.
//
// Rules (D-17, D-18, D-22):
//   - Only `vault.create()`; the mutating sibling API is forbidden on
//     problem-note territory (grep-gated via scripts/grep-no-vault-modify.sh).
//   - If the file exists (user opened and kept it, or added custom views):
//     no-op.
//   - If the user deletes it deliberately: the plugin does NOT auto-recreate.
//     (Same preservation posture as Phase 4's technique notes.)
//   - Folder auto-create: if the problems folder itself doesn't exist yet,
//     `vault.create` would throw ENOENT-equivalent. Create the folder first
//     via `vault.createFolder` (Obsidian 1.4.0+ — covered by D-19's 1.10.0
//     minAppVersion bump).
//
// Folder canonicalisation uses the same `.replace(/[\\/]+$/, '')` trailing-
// slash strip SettingsStore.sanitizeFolder uses, so both modules agree on
// the canonical form (Pattern Map: `src/notes/BaseFile.ts` folder-strip).

import type { App } from 'obsidian';

/**
 * Build the YAML content for the `LeetCode.base` file.
 *
 * Exported separately so tests can assert on the content without running
 * `ensureLeetcodeBase` (which requires a mocked Vault).
 *
 * Schema reverse-engineered (GAP-6) from an Obsidian 1.10+ UI-generated
 * `.base` file so the view actually renders. Key shape:
 *   - `filters:` lives INSIDE the view (not top-level)
 *   - Filter expression is `!note["lc-slug"].isEmpty()` — self-targeting by
 *     frontmatter presence (folder-agnostic: if the user relocates a problem
 *     note to a sub-folder it still appears in the Base view). lc-slug is the
 *     ONLY identity key the plugin still writes (template v2 retired lc-id).
 *   - Table columns mirror the user's template vocabulary (分类/难度/情况 +
 *     plugin-internal lc-status), sorted by `created` DESC (most recently
 *     fetched first)
 *
 * The `folder` parameter is retained for API compatibility with the
 * pre-GAP-6 signature but is not used in the rendered YAML (the filter
 * expression does not reference folder path).
 */
export function leetcodeBaseYaml(folder: string): string {
  // The signature retains `folder` for API compatibility with the pre-GAP-6
  // call sites (ensureLeetcodeBase below still passes the trimmed folder).
  // The new YAML schema's filter expression no longer references the folder
  // path, so the value is intentionally unused here.
  void folder;
  return [
    '# Auto-generated by the LeetCode plugin on first problem open.',
    '# Feel free to customise views, columns, filters, and sort — the plugin',
    '# will NOT overwrite this file. Delete it to regenerate on next open.',
    'views:',
    '  - type: table',
    '    name: Problems',
    '    filters:',
    '      and:',
    `        - '!note["lc-slug"].isEmpty()'`,
    '    order:',
    '      - file.name',
    '      - 分类',
    '      - 难度',
    '      - 情况',
    '      - lc-status',
    '    sort:',
    '      - property: created',
    '        direction: DESC',
    '',
  ].join('\n');
}

/**
 * GAP-6 migration helper.
 *
 * Returns true if the given file contents match the v0.1.0 broken YAML that
 * shipped before this gap-closure plan — i.e. the contents include BOTH of
 * the known-unique substrings from the broken schema:
 *   - `file.inFolder("` (folder-scoped filter expression)
 *   - `lc-id != null` (property-null filter expression)
 *
 * Both substrings are exact literal tokens from our broken ship; a user who
 * has customised the file away from the defaults will not carry both.
 *
 * Used by main.ts on plugin load to fire a one-time "you may want to
 * regenerate" Notice WITHOUT auto-overwriting (D-18 never-overwrite).
 */
export function isLegacyLeetcodeBaseV010(contents: string): boolean {
  if (typeof contents !== 'string' || contents.length === 0) return false;
  return contents.includes('file.inFolder("') && contents.includes('lc-id != null');
}

/**
 * Create `{folder}/LeetCode.base` if-and-only-if it does not already exist.
 *
 * - Returns silently on both paths (created / already-present).
 * - Any unexpected error (vault.create throws) propagates to the caller; the
 *   orchestrator (NoteWriter) invokes this in a non-critical path and does
 *   NOT await-throw into user-facing state. Callers typically wrap in try/catch
 *   when the write is purely opportunistic.
 */
export async function ensureLeetcodeBase(app: App, folder: string): Promise<void> {
  const trimmed = folder.replace(/[\\/]+$/, '');
  const path = `${trimmed}/LeetCode.base`;

  // D-18: never overwrite. Check existence first.
  const existing = app.vault.getAbstractFileByPath(path);
  if (existing) return;

  // Ensure the folder exists — `vault.create` is a leaf operation and won't
  // auto-create intermediate folders.
  const folderExists = app.vault.getAbstractFileByPath(trimmed);
  if (!folderExists) {
    await app.vault.createFolder(trimmed);
  }

  await app.vault.create(path, leetcodeBaseYaml(trimmed));
}
